### ISSUE TITLE
Needs at least serde version 1.0.119

### ISSUE THREAD

**Issue by jannic** [svenstaro/mt940-rs#55]
When trying to compile mt940 with serde <= 1.0.118, I get a lot of error messages like this:
```
    Checking mt940 v1.0.1
error[E0433]: failed to resolve: could not find `__private` in `_serde`
 --> /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/mt940-1.0.1/src/transaction_types.rs:9:39
  |
9 | #[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize, EnumString, EnumIter)]
  |                                       ^^^^^^^^^ could not find `__private` in `_serde`
  |
  = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `__private` in `_serde`
 --> /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/mt940-1.0.1/src/transaction_types.rs:9:50
  |
9 | #[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize, EnumString, EnumIter)]
  |                                                  ^^^^^^^^^^^ could not find `__private` in `_serde`
  |
  = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Of course, serde 1.0.118 is rather old, so I only noticed it when adding mt940 to an older project with an existing `Cargo.lock`.

I think it's not worth the effort to find out what's going wrong. But mt940-rs should specify that it needs at least 1.0.119 in it's `Cargo.toml`.

**Comment by svenstaro** [comment]
Actually I think this sounds like an incompatibility within your application. Could there maybe be two different versions of serde be in use? I don't think this is specific to a particular version of serde.

**Comment by jannic** [comment]
This was my initial guess, as well. But the error can be triggered in an empty project (result of `cargo new`) by only adding dependencies on mt940 and serde to Cargo.toml. (With the dependency on serde having a pinned version, e.g. `serde = "=1.0.118"`.
This happens with many versions of serde, I found the first working one by doing a binary search.
